[project]
name = "teleprompter"
version = "0.1.0"
description = "A simple teleprompter app"
authors = [
    {name = "Michael VanDyke",email = "michaeljamesvandyke@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6 (>=6.9.1,<7.0.0)",
    "markdown (>=3.8.2,<4.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
